[versions]
kotlin = "2.1.0"
kotest = "5.8.0"
coroutines = "1.8.0"
detekt = "1.23.5"
atomicfu = "0.23.2"
benchmark = "0.4.10"
dokka = "1.9.10"
bignum = "0.3.10"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
bignum = { module = "com.ionspin.kotlin:bignum", version.ref = "bignum" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
benchmark = { id = "org.jetbrains.kotlinx.benchmark", version.ref = "benchmark" }
